services:
  ollama:
    image: ollama/ollama:0.2.0           # ← pin
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
  qdrant:
    image: qdrant/qdrant:v1.9.0          # ← pin
    container_name: qdrant
    ports: ["6333"]                      # internal only
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks: ["agentnet"]
  langfuse:
    image: ghcr.io/langfuse/langfuse:3.74.0  # multi-arch
    container_name: langfuse
    ports: ["3000"]                       # internal only
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
      # keys injected via .env
    networks: ["agentnet"]
  postgres:
    image: postgres:16.2-alpine           # ← pin
    container_name: postgres
    ports: ["5432"]                       # internal only
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks: ["agentnet"]
  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    ports: ["7687"]                       # internal only
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    volumes:
      - ./data/neo4j:/data
      - ./constraints.cypher:/docker-entrypoint-initdb.d/constraints.cypher:ro
    networks: ["agentnet"]

networks:
  agentnet:
    driver: bridge
