version: '3.9'
services:
  ollama:
    image: ollama/ollama:0.2.0           # ← pin
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
  qdrant:
    image: qdrant/qdrant:v1.9.0          # ← pin
    container_name: qdrant
    ports: ["6333"]                      # internal only
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks: ["agentnet"]
  langfuse:
    image: ghcr.io/langfuse/langfuse:2.3.1  # ← pin
    container_name: langfuse
    ports: ["3000"]                       # internal only
    environment:
      LANGFUSE_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      # keys injected via .env
    networks: ["agentnet"]
  postgres:
    image: postgres:16.2-alpine           # ← pin
    container_name: postgres
    ports: ["5432"]                       # internal only
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks: ["agentnet"]

networks:
  agentnet:
    driver: bridge
