site_name: Personal Agentic OS
repo_url: https://github.com/adrianwedd/personal-agentic-operating-system
edit_uri: blob/main/
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
  logo: _assets/logo.svg
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list
plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
nav:
  - Home: index.md
  - Quick-start: quickstart.md
  - Architecture:
      - Overview: architecture/overview.md
      - LangGraph flow: architecture/langgraph_flow.md
  - Guides:
      - Ingestion Pipeline: guides/ingestion_pipeline.md
      - HITL Workflow: guides/hitl_workflow.md
      - ClickHouse Tuning: guides/clickhouse_tuning.md
  - API Reference: api/index.md
  - Changelog: changelog.md
