name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant:v1.9.0
        ports: ["6333:6333"]
      neo4j:
        image: neo4j:5.20
        env:
          NEO4J_AUTH: neo4j/password
        ports: ["7687:7687"]
    steps:
      - uses: actions/checkout@v4
      - uses: astrojuanlu/setup-uv@v1
      - run: uv pip install -r requirements.txt
      - run: uv pip install pytest pytest-cov ruff
      - run: ruff .
      - run: |
          export NEO4J_URI=bolt://localhost:7687
          export NEO4J_URL=$NEO4J_URI
          export NEO4J_AUTH=neo4j/password
          pytest -q --cov=agent --cov-fail-under=80

  smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d --pull always
      - run: make smoke
      - run: docker compose down
