name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      qdrant:
        image: qdrant/qdrant:v1.9.0
        ports: ["6333:6333"]
    steps:
      - uses: actions/checkout@v4
      - uses: astrojuanlu/setup-uv@v1
      - run: uv pip install -r requirements.txt
      - run: uv pip install pytest pytest-cov ruff
      - run: ruff .
      - run: pytest -q --cov=agent --cov-fail-under=80
