name: Docs
on:
  push:
    tags: ["v*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pip install mkdocs-material mkdocstrings-python mike
      - run: mike deploy --update-aliases "$(git describe --tags)" latest
      - run: mike set-default latest
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
